---
# note: when the server was booted into rescue mode already it will still return active = false
# active = true only appears when rescue mode was activated but the system not yet re-booted 
- name: check the current rescue mode state
  uri:
    url: "https://robot-ws.your-server.de/boot/{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}/rescue"
    method: GET
    user: "{{ hetzner_installimage_webservice_username }}"
    password: "{{ hetzner_installimage_webservice_password }}"
    force_basic_auth: yes
    status_code: 200
  delegate_to: localhost
  register: hetzner_installimage_rescue
  when: hetzner_installimage_run

- name: activate rescue mode
  uri:
    url: "https://robot-ws.your-server.de/boot/{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}/rescue"
    method: POST
    user: "{{ hetzner_installimage_webservice_username }}"
    password: "{{ hetzner_installimage_webservice_password }}"
    force_basic_auth: yes
    body: "os=linux&arch=64&authorized_key={{ hetzner_installimage_key_fingerprint }}"
    status_code: 200
    body_format: form-urlencoded
  delegate_to: localhost
  when: hetzner_installimage_rescue.json.rescue.active == false

- name: Execute hardware reset
  uri:
    url: "https://robot-ws.your-server.de/reset/{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    method: POST
    user: "{{ hetzner_installimage_webservice_username }}"
    password: "{{ hetzner_installimage_webservice_password }}"
    force_basic_auth: yes
    body: "type=hw"
    status_code: 200
    body_format: form-urlencoded
  delegate_to: localhost
  register: reset

- name: remove ssh keys per host
  include_tasks: modify_known_hosts.yml
  vars:
    modify_known_hosts_state: absent
  loop: "{{ ansible_play_batch }}"
  run_once: true

- name: pause a bit for the hardware reset to kick in
  pause: seconds=15
  delegate_to: localhost

- name: waiting for server to come back
  wait_for:
    host: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    port: 22
    delay: 1
    timeout: "{{ hetzner_installimage_wait_timeout_after_reset }}"
  delegate_to: localhost

- name: add ssh keys per host
  include_tasks: modify_known_hosts.yml
  vars:
    modify_known_hosts_state: present
  loop: "{{ ansible_play_batch }}"
  run_once: true
